name: ATPR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Make
      uses: bazhenov/action-avr-make@v1
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ATPR-${{ github.run_number }}
        path: build/ATPR.elf
